name: pangeo
channels:
  - conda-forge
  - intake
  - default
dependencies:
  - python=3.7
  - pyarrow
  - xarray
  - dask
  - distributed
  - gcsfs
  - nomkl
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - jupyter
  - ipywidgets
  - graphviz
  - nodejs
  - jupyterlab=0.35
  - matplotlib
  - scikit-learn
  - nbserverproxy
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/dask/dask-kubernetes@master
